server:
  port: 2003


spring:
  application:
    name: seata-account-service
  cloud:
    nacos:
      discovery:
        server-addr: @nginxIP@:80
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://@baseIp@:3306/seata_account?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

    #以下为新增
    druid:
      # 指明是否在从池中取出连接前进行检验,如果检验失败, 则从池中去除连接并尝试取出另一个，
      #注意: 设置为true后如果要生效,validationQuery参数必须设置为非空字符串
      test-on-borrow: false
      # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
      #注意: 设置为true后如果要生效,validationQuery参数必须设置为非空字符串
      test-while-idle: true
      # 指明是否在归还到池中前进行检验，注意: 设置为true后如果要生效,
      #validationQuery参数必须设置为非空字符串
      test-on-return: false
      # SQL查询,用来验证从连接池取出的连接,在将连接返回给调用者之前.
      #如果指定,则查询必须是一个SQL SELECT并且必须返回至少一行记录
      validation-query: select 1

# seata 配置
seata:
  # 分布式事务分组
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: true
  data-source-proxy-mode: AT

  # seata配置中心
  config:
    type: nacos
    nacos:
      namespace: b3dc76dd-a21e-44fb-9dd3-63e726a51073  #在安装seata目录下的conf中的register.conf的config节点中下的nacos节点的namespace。如果没有配置 默认public空间
      # nacos配置中心地址
      server-addr: @baseIp@:80
      # 分组
      group: SEATA_GROUP
      # nacos的账号和密码
      userName: nacos
      password: nacos
      data-id: "seataServer.properties"
  # seata的注册中心
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: @baseIp@:80
      namespace: b3dc76dd-a21e-44fb-9dd3-63e726a51073   #在安装seata目录下的conf中的register.conf的register节点中下的nacos节点的namespace。如果没有配置 默认public空间
      userName: nacos
      password: nacos
      group: SEATA_GROUP
  service:
    vgroup-mapping:
      my_test_tx_group: default    #这里要特别注意和nacos中配置的要保持一直


feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
