server:
  port: 9003

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: @nginxIP@:80 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'