server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: @baseIp@:80 #Nacos服务注册中心地址
    sentinel:
      transport:
        dashboard: @baseIp@:@sentinelIp@ #配置Sentinel dashboard地址
        port: 8719
        clientIp: docker.for.mac.host.internal
#      datasource:
#        ds1:
#          nacos:
#            server-addr: localhost:8848
#            dataId: ${spring.application.name}
#            groupId: DEFAULT_GROUP
#            data-type: json
#            rule-type: flow

# 监控
management:
  endpoints:
    web:
      exposure:
        include: '*'